services:

  client:
    build:
      dockerfile: ./clients/webapp/dev.Dockerfile
    working_dir: /app
    volumes:
      - ./clients/webapp:/app
    ports:
      - "127.0.0.1:5173:5173"
    tty: false
    logging:
      driver: none

  server:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/app
    env_file:
      - dev.env
    depends_on:
      - "postgres"
    tty: true

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev
    tty: false
    logging:
      driver: none